### ISSUE TITLE
Missing Requirements

### ISSUE THREAD

**Issue by chancecardona** [SixK/sam2coco_server#1]
https://github.com/SixK/sam2coco_server/blob/46832492af2639f427b1de9811d07df9b2db9ce9/requirements.txt#L3
Should also include 
```
pycocotools
opencv-python
torch
torchvision
```

**Comment by SixK** [comment]
Thank's for report.
Commit 87ddb1993cf0e83bf50841dc3c76617db201eb7b should add missing dependencies
